### ISSUE TITLE
Reservation Edit Save Button Not Working

### ISSUE THREAD

**Issue by john-rey-edralin** [john-rey-edralin/stsweng-1#101]
Steps to Reproduce:
1. Go to Reservations Page
2. Click any event
3. click edit
4. click submit
5. click submit again 
![image](https://user-images.githubusercontent.com/80669817/152629212-01b1bbe9-5af5-4ec8-b9cb-ba06fc89da16.png)

**Comment by john-rey-edralin** [comment]
Same issue with creating an event of US#5 I can't create an event because it is stuck on Confirm Submit

**Comment by sophia-vista** [comment]
Fixed
