### ISSUE TITLE
Saving modified information not working

### ISSUE THREAD

**Issue by john-rey-edralin** [john-rey-edralin/stsweng-1#13]
The edit page takes too long to load, and after submission, it loads again that way but returns to the previous information.

**Comment by john-rey-edralin** [comment]
Steps to reproduce:
1. Select an already made reservation then click edit
![image](https://user-images.githubusercontent.com/80669817/145948784-e1a1fa87-9ee0-4bcb-bb6b-731de85ee621.png)
2. Expect to have a long loading time stuck in this screen below
![image](https://user-images.githubusercontent.com/80669817/145948881-72621f24-875d-4ca0-944e-400b25354595.png)
3. From the original Client Name: Mare
![image](https://user-images.githubusercontent.com/80669817/145948960-d12674da-227d-4e15-8628-6cac0722d41d.png)
3.1 Change Client Name to Bared
![image](https://user-images.githubusercontent.com/80669817/145949151-b1194850-3c54-457f-812f-4142fa5aeb40.png)
4. Click Submit and expect another long loading time
![image](https://user-images.githubusercontent.com/80669817/145949239-8b65bf32-f69b-4641-8714-9e530c66e373.png)
5. The modified Client Name: Bared was reverted back to Client Name: Mare
![image](https://user-images.githubusercontent.com/80669817/145949316-92af466c-e520-4791-850c-a9dcc441f9b7.png)

**Comment by Zet-Warden** [comment]
fixed!

**Comment by john-rey-edralin** [comment]
Pop-up submit button not working
![image](https://user-images.githubusercontent.com/80669817/145966026-a8164c96-06d8-414a-ac7e-547f5cc41129.png)

**Comment by UyyyL** [comment]
We are unable to reproduce this bug :(

**Comment by john-rey-edralin** [comment]
Tried restarting my laptop it works now on my side my bad.
