### ISSUE TITLE
Final payment goes to pencil booking not reservation

### ISSUE THREAD

**Issue by john-rey-edralin** [john-rey-edralin/stsweng-1#18]
Steps to Reproduce:
1. From home click "+" symbol
![image](https://user-images.githubusercontent.com/80669817/145979701-3c823bb5-2df4-4f18-96fc-2f8602f35b1a.png)
2. Fill in required details
![image](https://user-images.githubusercontent.com/80669817/145979854-e7b59502-1af9-411d-81f5-5bac743499cb.png)
3. Enter payment details then click submit
![image](https://user-images.githubusercontent.com/80669817/145979944-02280af7-96b4-47c9-a273-23fb1827072b.png)
4. Will be redirected to pencil bookings page
![image](https://user-images.githubusercontent.com/80669817/145980093-c151fed1-8537-423b-8213-e341dfed66a3.png)

**Comment by sophia-vista** [comment]
Fixed by disabling final payment when downpayment fields are empty. (cc: @ajmarcelo)

**Comment by john-rey-edralin** [comment]
Approved.
