### ISSUE TITLE
Downpayment without input on Amount Paid

### ISSUE THREAD

**Issue by john-rey-edralin** [john-rey-edralin/stsweng-1#19]
It is accepting null values on Amount Paid
![image](https://user-images.githubusercontent.com/80669817/145981124-e0ae1cf8-a1a9-4d42-963d-1aad0fad1c8c.png)

**Comment by john-rey-edralin** [comment]
The null value is also showing when checking event details
![image](https://user-images.githubusercontent.com/80669817/145981514-2ccd7601-a871-400e-b767-ba97a123d5d3.png)

**Comment by sophia-vista** [comment]
Fixed. (cc @ajmarcelo)

**Comment by john-rey-edralin** [comment]
Approved.
