### ISSUE TITLE
 Menu Details bug

### ISSUE THREAD

**Issue by john-rey-edralin** [john-rey-edralin/stsweng-1#22]
Steps to reproduce:
1. Create an Event
2. Select Event Venue and Package as stated below
![image](https://user-images.githubusercontent.com/80669817/145992321-87fdbebd-8609-4922-901b-b6aae6780599.png)
3. Select all food as stated below
![image](https://user-images.githubusercontent.com/80669817/145992422-d3abcd4a-e047-4ead-8596-a54ec639d2e3.png)
4. Select Event Venue and Package as stated below
![image](https://user-images.githubusercontent.com/80669817/145992544-89c45de1-fdf7-46c4-b2b2-a285ecdcc99c.png)
5. Select a food as stated below
![image](https://user-images.githubusercontent.com/80669817/145992671-11a09d8e-1b88-43eb-832e-71bc52341369.png)
6. Select that food again. It will add chicken to the list and it should not be allowed
![image](https://user-images.githubusercontent.com/80669817/145992712-2d2b4120-1475-4581-8b33-89cdf6973da2.png)

**Comment by sophia-vista** [comment]
Fixed.

**Comment by john-rey-edralin** [comment]
Approved.
