### ISSUE TITLE
No error prompt if invalid food name

### ISSUE THREAD

**Issue by john-rey-edralin** [john-rey-edralin/stsweng-1#26]
Steps to reproduce:
1. Create a new event
2. Fill in  Event Details information
3. Head to Menu Details add Additional Food
![image](https://user-images.githubusercontent.com/80669817/146112007-45ecbe66-1ad6-431f-8af6-a071b935ff12.png)

**Comment by sophia-vista** [comment]
Fixed. Typed input is now automatically deleted if food name is invalid.
