### ISSUE TITLE
US#5 mobile number

### ISSUE THREAD

**Issue by john-rey-edralin** [john-rey-edralin/stsweng-1#3]
Invalid example for a mobile number in a selected country like in Ph where it is expected 11 numbers but 8 are shown in the example instead.
![image](https://user-images.githubusercontent.com/80669817/145763161-a9438266-7003-46c4-bf22-fa0fba89b438.png)

**Comment by sophia-vista** [comment]
Fixed!

**Comment by john-rey-edralin** [comment]
Approved.
