### ISSUE TITLE
Leaving the Create Event page redirects to the Reservations Page

### ISSUE THREAD

**Issue by sophia-eguaras** [john-rey-edralin/stsweng-1#41]
### Description
Using the return button in the create event page redirects the user to the reservations page.

### Steps to Reproduce with Visual Proof

**1.** From home click "`+`"
![image](https://user-images.githubusercontent.com/80721700/149074797-67a9d135-78ce-47a0-8a6d-a3369aac2517.png)

**2.** In the Create Event page, click the "`<`"
![image](https://user-images.githubusercontent.com/80721700/149074945-3c0c6459-6a89-4e37-8d52-5d2f30f26c89.png)

**3.** Press "`Exit`" on the dialogue box
![image](https://user-images.githubusercontent.com/80721700/149074986-d5da050b-e6ca-4fb8-8cf7-aa0dfeee3a0e.png)

**4.** Page is redirected to the reservations page
![image](https://user-images.githubusercontent.com/80721700/149080779-bfbde45c-1043-4381-82ae-6b1366bb8a13.png)

### Expected Results
User is redirected back to the **HOME** page

### Actual Results
User is redirected to **RESERVATIONS** page

### Additional Information
| Software |  |
| --- | --- |
| **Browser** | Microsoft Edge (V97) |
| **Operating System** | Windows 10 |

**Comment by sophia-vista** [comment]
Removed the modal for exiting the form (User may navigate back to the previous page using the browser's back button instead).
