### ISSUE TITLE
Leaving the Edit Pencil Booking page redirects to the Reservation page

### ISSUE THREAD

**Issue by sophia-eguaras** [john-rey-edralin/stsweng-1#42]
### Description
Opening a pencil booking event to edit and then leaving the page (i.e. any changes will not be saved) will redirect it to the Reservations Page.

### Steps to Reproduce with Visual Proof
1. In the **Home** page, click the "**Event List**" tab and select "**Pencil Bookings**" from the dropdown menu.
![image](https://user-images.githubusercontent.com/80721700/149089869-912db6c4-bd3d-4d29-9b70-5d3bb700ca89.png)

2. In the **Pencil Bookings** page, click an event dated today or onwards (preferably onwards). (**Note**: this was done on `01/12/2022`. Hence, the event dated on `01/13/2021` was selected)
![image](https://user-images.githubusercontent.com/80721700/149090032-8386bf75-2cb7-4cbb-879c-b1d0a000cb91.png)

3. Click "**Edit**" in the modal.
![image](https://user-images.githubusercontent.com/80721700/149091650-a4f9e27d-6c1e-4d55-815e-8d4d92b350fe.png)

4. In the **Edit** page, click the "`<`" on the upper left corner of the page.
![image](https://user-images.githubusercontent.com/80721700/149091697-0fac57cc-edcf-4c8e-82b6-a791b2a051a4.png)

5. Click "`Exit`" on the dialogue box
![image](https://user-images.githubusercontent.com/80721700/149091757-5244d60e-796a-40ef-8eda-169561c78e4e.png)

6. Page is redirected to the reservations page.
![image](https://user-images.githubusercontent.com/80721700/149091825-16aa4a65-5f68-4cec-95b3-766e1a20349b.png)

### Expected Results
User is redirected back to the **RESERVATIONS** page

### Actual Results
User is redirected to **PENCIL BOOKINGS** page

### Additional Information
| Software |  |
| --- | --- |
| **Browser** | Microsoft Edge (V97) |
| **Operating System** | Windows 10 |

**Comment by sophia-vista** [comment]
Removed the modal for exiting the form (User may navigate back to the previous page using the browser's back button instead).
