### ISSUE TITLE
[Confirm Submit - Submit Button] not working

### ISSUE THREAD

**Issue by john-rey-edralin** [john-rey-edralin/stsweng-1#47]
Steps to reproduce:
1. Go to the Reservations page
2. Select any events and click edit
3. click Submit button
![image](https://user-images.githubusercontent.com/80669817/149263541-e2545918-f04e-40f0-bbbc-472731481ccd.png)
4. click Submit button 
![image](https://user-images.githubusercontent.com/80669817/149263577-3493c592-187c-4129-ac09-6f2a22ce5cf1.png)

**Comment by sophia-vista** [comment]
Cannot reproduce

**Comment by sophia-eguaras** [comment]
In my copy (currently testing 5, 6, 8, and 11), it can be reproduced.

**Comment by Zet-Warden** [comment]
Cannot reproduce issue on my end, tested under US#6-Modify-Reservation branch.

**Comment by sophia-eguaras** [comment]
Hmm, it doesn't seem to work on my end while testing it under the develop-new branch.

**Comment by Zet-Warden** [comment]
Seems like a merge issue. Pushed a fixed under develop-new just now.

**Comment by sophia-eguaras** [comment]
Thanks! It's working now
