### ISSUE TITLE
"Back" button on the "Mark as Done" Modal is not working

### ISSUE THREAD

**Issue by sophia-eguaras** [john-rey-edralin/stsweng-1#58]
### Description
Using the "`Back`" button when exiting/leaving the "**Mark as Done**" modal responds by making the **View Event** modal appear and disappear when clicked.

### Steps to Reproduce with Visual Proof
1. In the **Home** page, click the "**Event List**" tab and select "**Reservations**" from the dropdown menu.
![image](https://user-images.githubusercontent.com/80721700/149449408-06efb051-b309-4eaa-84f5-880fcce3f55d.png)

2. In the **Reservations** list page, click on an event to edit and click "`Mark as Done`" in the modal.
![image](https://user-images.githubusercontent.com/80721700/149450821-4a8a43ad-f8e9-4d1f-9e0d-7edc4137c900.png)

3. In the "**Mark as Done**" modal, click "`Back`".
![image](https://user-images.githubusercontent.com/80721700/149450912-f7716ffd-b306-4bf7-bab8-06520072ade6.png)

4. The "**View Event**" modal (i.e. the previous and larger modal) would disappear. However, it would appear again if the "`Back`" button is clicked again.
![image](https://user-images.githubusercontent.com/80721700/149451273-c6e80a2c-a045-4020-bf2d-60debe55f992.png)

### Expected Results
When the "Back" button is pressed on the "**Mark as Done**" modal, it **disappears** and leaves the "**View Event**" modal up.

### Actual Results
When the "Back" button is pressed on the "**Mark as Done**" modal, it **stays** on screen while the "**View Event**" modal disappears/appears

### Additional Information

| Software |  |
| --- | --- |
| **Browser** | Microsoft Edge (V97) |
| **Operating System** | Windows 10 |

**Comment by sophia-vista** [comment]
Fixed in #70
