### ISSUE TITLE
Events without final payment can be marked as done

### ISSUE THREAD

**Issue by sophia-eguaras** [john-rey-edralin/stsweng-1#59]
### Description
Events in the **Reservations** list page can be marked as done even if there is no final payment yet.

### Steps to Reproduce with Visual Proof
1. In the **Home** page, click the "**Event List**" tab and select "**Reservations**" from the dropdown menu.
![image](https://user-images.githubusercontent.com/80721700/149449408-06efb051-b309-4eaa-84f5-880fcce3f55d.png)

2. In the **Reservations** list page, click on an event to edit and click "`Mark as Done`" in the modal.
![image](https://user-images.githubusercontent.com/80721700/149487442-4536b163-baa7-47c9-ba93-b9a3900fdf5f.png)

3. In the "**Mark as Done**" modal, click "`Continue`".
![image](https://user-images.githubusercontent.com/80721700/149487236-ec06cae3-974d-4d6a-a191-d4e5e886553c.png)

4. Go to the **Past Events** list through the **Event List** tab and here you can see that the event without final payment is listed.
![image](https://user-images.githubusercontent.com/80721700/149487532-9d376b3c-86e2-4eb1-8a4b-32190113c40e.png)

### Expected Results
Reservations without final payment should not be able to be marked as done

### Actual Results
Reservations, even without final payment, can be marked as done.

### Additional Information

| Software |  |
| --- | --- |
| **Browser** | Microsoft Edge (V97) |
| **Operating System** | Windows 10 |

**Comment by sophia-vista** [comment]
Fixed in #70
