### ISSUE TITLE
No error message shown when there are no venues selected

### ISSUE THREAD

**Issue by sophia-eguaras** [john-rey-edralin/stsweng-1#60]
### Description
In editing a reservation event, there is no error message shown when there no venues are selected. (Note: There is an error message  for this when creating events and editing pencil booking events).

### Steps to Reproduce with Visual Proof
1. In the **Home** page, click the "**Event List**" tab and select "**Reservations**" from the dropdown menu.
![image](https://user-images.githubusercontent.com/80721700/149449408-06efb051-b309-4eaa-84f5-880fcce3f55d.png)

2. In the **Reservations** list page, click on an event to edit and click "`Edit`" in the modal.
![image](https://user-images.githubusercontent.com/80721700/149536630-3cb09208-6ce7-48de-9afd-960bdf7870a8.png)

3. In the **Edit Event** page, deselect the currently set venue(s) in the "**Event Venue and Package**" section.
![image](https://user-images.githubusercontent.com/80721700/149537019-b7b1bd76-320b-4bbb-9bd3-615ece23096f.png)

4. In the editing reservation events, there is no error message for this unlike in editing pencil bookings or creating a new event. Hence, there is a slight inconsistency with the validation.
![image](https://user-images.githubusercontent.com/80721700/149537062-f09b8a60-bb3e-4dcf-8d88-26a3e93d5b55.png)

### Expected Results
When there is no venue selected in the "**Event Venue and Package**" section when editing an event, it should show an error and should be consistent with all event related edits/creation.

### Actual Results
When there is no venue selected in the "**Event Venue and Package**" section when editing an event, **no** error message is shown but there is for editing pencil bookings.

### Additional Information

| Software |  |
| --- | --- |
| **Browser** | Microsoft Edge (V97) |
| **Operating System** | Windows 10 |

**Comment by sophia-vista** [comment]
Fixed
