### ISSUE TITLE
Events that have not passed yet can be marked as done

### ISSUE THREAD

**Issue by sophia-eguaras** [john-rey-edralin/stsweng-1#61]
### Description
When marking an reservation event done, events that have not been held yet can be marked as done when it shouldn't be.

### Steps to Reproduce with Visual Proof
1. In the **Home** page, click the "**Event List**" tab and select "**Reservations**" from the dropdown menu.
![image](https://user-images.githubusercontent.com/80721700/149265083-f6c8d92f-4693-4330-8833-98a3d72ac132.png)

2. In the **Reservations** list page, click on an event that has not reached the day its supposed to be held and click **`Mark as Done`** in the modal. 
![image](https://user-images.githubusercontent.com/80721700/149539377-b289c02f-e281-4e92-b8ee-85bdf8439423.png)

3. In the following modal, click "`Continue`". Here, it is possible to continue to mark it as done
![image](https://user-images.githubusercontent.com/80721700/149539444-c7bab59a-bc15-4c1b-95b8-17a2b2e3c01d.png)

4. In the **Past Events** list, the event marked as done earlier can be seen here although it has not been held yet.
![image](https://user-images.githubusercontent.com/80721700/149539677-07e806a5-8d8d-4386-84ae-dc420b55cb70.png)

### Expected Results
All events that have not passed its day of celebration should not be able to be marked as done.

### Actual Results
Any event, before or after its day of celebration, can be marked as done.

### Additional Information

| Software |  |
| --- | --- |
| **Browser** | Microsoft Edge (V97) |
| **Operating System** | Windows 10 |

**Comment by sophia-vista** [comment]
Fixed
