### ISSUE TITLE
Remove "Cancel Event" button in Cancelled Event list

### ISSUE THREAD

**Issue by sophia-eguaras** [john-rey-edralin/stsweng-1#78]
### Suggestion
The "`Back`" button in the Cancel Event modal could be removed. <Reason>

### Steps to Reproduce
1. In the **Home** page, click the "**Event List**" tab and select "**Cancelled Events**" from the dropdown menu.

2. In the **Cancelled Events** list page, click on an event.

3. In the "**View Event**" modal, the "Cancel Event" button there should be removed.

### Expected Results
The back button in the Cancel Event modal is removed.

### Additional Information
The "Cancel event" modal is shown on any event (Reservation/Pencil Booking). The one above is just an example

| Software |  |
| --- | --- |
| **Browser** | Microsoft Edge (V97) |
| **Operating System** | Windows 10 |

**Comment by sophia-vista** [comment]
This be fixed w/ the merge fix
