### ISSUE TITLE
Add a color scheme legend for the events

### ISSUE THREAD

**Issue by sophia-eguaras** [john-rey-edralin/stsweng-1#80]
### Suggestion
Add a legend to show what the colors of the events shown in the Home page represents. Currently, the color scheme is that Reservation events are red while Pencil Booking events are Green. The user might not be aware of this hence the suggestion of adding a legend. Below is what I meant by "Legend" (i.e. the colored squares at the bottom of the chart). However, you are free to be creative in how you're going to show it in the web app.
![image](https://user-images.githubusercontent.com/80721700/150671870-8f2a0737-ac9c-4edb-8ec5-8487dac45533.png)

### Steps to Reproduce with Visual Proof
![image](https://user-images.githubusercontent.com/80721700/150672445-6b350f57-724f-4464-abda-4bf3580a6c01.png)

### Expected Results
There are "legends" to show what the colors are meant to represent in the Home page

### Additional Information

| Software |  |
| --- | --- |
| **Browser** | Microsoft Edge (V97) |
| **Operating System** | Windows 10 |

**Comment by sophia-vista** [comment]
Implemented
