### ISSUE TITLE
View Event modal in calendar page does not appear

### ISSUE THREAD

**Issue by sophia-eguaras** [john-rey-edralin/stsweng-1#81]
### Description
Viewing a specific event in the calendar does not display its respective modal

### Steps to Reproduce with Visual Proof
1. In the **Home** page, click the **Calendar** tab from the navigation bar
![image](https://user-images.githubusercontent.com/80721700/150807481-405a2c3c-6f78-47c5-93b3-a1fb42dd4cf6.png)

2. In the **Calendar** page, select any day that has events.
![image](https://user-images.githubusercontent.com/80721700/150807571-08a1829a-f9d5-453d-ac88-29135c9a293b.png)

3. In the list of events listed for that day, select any event to view its details. The **View Event** modal for the event does not show up and the whole events list modal disappears with a greyed out background.
![image](https://user-images.githubusercontent.com/80721700/150807640-8c62f0e5-9c97-45ae-99e9-686d06f2ac59.png)

### Expected Results
When a specific event is clicked in the **Calendar** page, it should display its respective **View Event** modal.

### Actual Results
When a specific event is clicked in the **Calendar** page, there is no **View Event** modal for it and the whole events list modal disappears.

### Additional Information

| Software |  |
| --- | --- |
| **Browser** | Microsoft Edge (V97) |
| **Operating System** | Windows 10 |

**Comment by sophia-vista** [comment]
Fixed na pala
