### ISSUE TITLE
Username of currently signed-in user is not displayed

### ISSUE THREAD

**Issue by sophia-eguaras** [john-rey-edralin/stsweng-1#92]
### Description
When signing is as a specific user, their username is not displayed in the top right corner of the page after logging in. Instead of the username of the currently signed-in user, the word "**USERNAME**" is displayed instead.

### Steps to Reproduce with Visual Proof
1. In the log-in page, log in as a valid user.
![image](https://user-images.githubusercontent.com/80721700/151945990-90b96f81-b0a4-4b84-af92-d2017c25257f.png)

2. Inspect the top right corner of the page. It does not display the currently logged in user.
![image](https://user-images.githubusercontent.com/80721700/151946030-8fdf8db4-de37-45cd-aeba-cddabf8a2ac2.png)

### Expected Results
The username of the currently signed-in user is displayed in the top right corner of the page after logging in.

### Actual Results
The username of the currently signed-in user is **not** displayed in the top right corner of the page after logging in and is instead replaced with the word "**USERNAME**".

### Additional Information

| Software |  |
| --- | --- |
| **Browser** | Microsoft Edge (V97) |
| **Operating System** | Windows 10 |

**Comment by john-rey-edralin** [comment]
1. After merging it shows an error for this issue fix
![image](https://user-images.githubusercontent.com/80669817/152620289-b75557a7-1989-4de0-bd84-b427570c8e74.png)
